### ISSUE TITLE
Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by SeMax1337** [NorvikIT/nuxt-utm-adder#1]
![image](https://user-images.githubusercontent.com/48476180/162689214-4059b6a9-ec56-4670-92a3-9a19f72caea3.png)
when the 'a' tag does not have the href attribute or href="", errors are poured into the console

can you do an elementary check of the <a> tag for the presence of href and href !== '' && '#' ?

I also found errors when the 'article' tag tries to get href

![image](https://user-images.githubusercontent.com/48476180/162691416-75c98941-ab36-4b6f-af4a-c388abe92a60.png)

**Comment by vaban-ru** [comment]
@SeMax1337 Hey! Sorry for the delay! Thanks for the info, we'll fix it as soon as possible!

**Comment by vaban-ru** [comment]
@SeMax1337 Hey! We released a [new version](https://github.com/NorvikIT/nuxt-utm-adder/releases/tag/v1.1.4) of the plugin and fixed the bugs, thanks for the help!
